dailyfresh/apps/cart/urls.py
#-*-coding:utf-8-*-
from django.contrib import admin
from django.urls import path
from cart.views import CartAddView, CartInfoView, CartUpdateView, CartDeleteView

app_name = 'cart'
urlpatterns = [
        path('add/', CartAddView.as_view(), name='add'),
        path('cart/', CartInfoView.as_view(), name='cart'),
        path('delete/', CartDeleteView.as_view(), name='delete'),
        path('update/', CartUpdateView.as_view(), name='update')

]

dailyfresh/apps/goods/urls.py
#-*-coding:utf-8-*-
from django.contrib import admin
from django.urls import path
from goods.views import IndexView, DetailView, ListView

app_name = 'goods'
urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('detail/<int:id>/', DetailView.as_view(), name='detail'),
    path('list/<int:type_id>/<int:page>/', ListView.as_view(), name='list')
]

dailyfresh/apps/user/urls.py
#-*-coding:utf-8-*-
from django.contrib import admin
from django.urls import path
from user.views import RegisterView, LoginView, ActiveView, LoginoutView, UserInfoView, UserOrderView, UserSiteView
from order.views import OrderPayView, CheckPayView

app_name = 'user'
urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('active/str<token>/', ActiveView.as_view(), name='active'),
    path('logout/', LoginoutView.as_view(), name='logout'),

    path('', UserInfoView.as_view(), name='user'),
    path('order/int<page>/', UserOrderView.as_view(), name='order'),
    path('address/', UserSiteView.as_view(), name='address'),
    path('pay/', OrderPayView.as_view(), name='pay'),
    path('check/', CheckPayView.as_view(), name='check')
]

dailyfresh/dailyfresh/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('goods.urls')),
    path('user/', include('user.urls')),
    path('order/', include('order.urls')),
    path('cart/', include('cart.urls')),
    path('tinymce/', include('tinymce.urls')),
    path('search', include('haystack.urls'))
]

dailyfresh/apps/cart/views.py
from django.shortcuts import render, reverse, redirect
from django.http import JsonResponse
from django.views import View
from django_redis import get_redis_connection

from utils.mixin import LoginRequiredMixin
from goods.models import GoodsSKU

# Create your views here.

#/cart/add
#用ajax post请求
class CartAddView(View):
    def post(self, request):

        # 从前台接收加入购物车的商品id和商品的count
        user = request.user
        if not user.is_authenticated:
            return JsonResponse({'ret': 0, 'errmsg': '请先登录'})
        id = request.POST.get('good_id')
        count = request.POST.get('count')

        #校验数据
        if not all([id, count]):
            return JsonResponse({'ret': 1, 'errmsg': '数据不全'})
        try:
            count = int(count)
        except Exception as e:
            return JsonResponse({'ret': 2, 'errmsg': '商品数量有误'})
        try:
            sku = GoodsSKU.objects.get(id=id)
        except GoodsSKU.DoesNotExist:
            return JsonResponse({'ret': 3, 'errmsg': '该商品不存在'})

        # 将这些数据存入redis
        conn = get_redis_connection('default')
        cart_key = 'cart_%d' % user.id
        cart_count = conn.hget(cart_key, id)
        if cart_count:
            count += int(cart_count)
        if count > sku.stock:
            return JsonResponse({'ret': 4, 'errmsg': '库存不足'})
        conn.hset(cart_key, id, count)
        total_count = conn.hlen(cart_key)
        return JsonResponse({'ret': 5, 'total_count': total_count, 'msg': '添加成功'})


class CartInfoView(LoginRequiredMixin, View):
    def get(self, request):
        user = request.user
        #从redis 中取出购物车数据
        conn = get_redis_connection('default')
        cart_key = 'cart_%d' % user.id
        #从redis获取所有购物车商品的id并从数据库中取出其sku
        cart_skus = conn.hgetall(cart_key)

        total_count = 0
        total_price = 0
        skus = []
        for sku_id, count in cart_skus.items():
            sku = GoodsSKU.objects.get(id=sku_id)
            sku_price = sku.price * int(count)
            sku.sku_price = sku_price
            sku.sku_count = count
            skus.append(sku)
            total_count += int(count)
            total_price += sku_price
        #整理数据
        context = {'skus': skus,
                   'total_count': total_count,
                   'total_price': total_price

        }
        return render(request, 'cart.html', context)


class CartUpdateView(View):
    def post(self, request):
        user = request.user
        if not user.is_authenticated:
            return JsonResponse({'ret': 0, 'errmsg': '请先登录'})
        id = request.POST.get('good_id')
        count = request.POST.get('count')

        # 校验数据
        if not all([id, count]):
            return JsonResponse({'ret': 1, 'errmsg': '数据不全'})
        try:
            count = int(count)
        except Exception as e:
            return JsonResponse({'ret': 2, 'errmsg': '商品数量有误'})
        try:
            sku = GoodsSKU.objects.get(id=id)
        except GoodsSKU.DoesNotExist:
            return JsonResponse({'ret': 3, 'errmsg': '商品不存在'})

        if count > sku.stock:
            return JsonResponse({'ret': 4, 'errmsg': '库存不足'})
        conn = get_redis_connection('default')
        cart_key = 'cart_%d' % user.id
        conn.hset(cart_key, id, count)
        #计算用户购物车中商品的总件数
        total_count = 0
        vals = conn.hvals(cart_key)
        for val in vals:
            total_count += int(val)
        return JsonResponse({'ret': 5, 'total_count': total_count, 'msg': '更新成功'})



class CartDeleteView(View):
    def post(self, request):
        user = request.user
        if not user.is_authenticated:
            return JsonResponse({'ret': 0, 'errmsg': '请先登录'})
        id = request.POST.get('good_id')
        #校验数据
        if not id:
            return JsonResponse({'ret': 1, 'errmsg': '无效的商品id'})
        try:
            sku = GoodsSKU.objects.get(id=id)
        except GoodsSKU.DoesNotExist:
            return JsonResponse({'ret': 2, 'errmsg': '商品不存在'})
        #删除购物车中的数据
        conn = get_redis_connection('default')
        cart_key = 'cart_%d' % user.id
        conn.hdel(cart_key, id)
        # 计算用户购物车中商品的总件数
        total_count = 0
        vals = conn.hvals(cart_key)
        for val in vals:
            total_count += int(val)
        return JsonResponse({'ret': 3, 'total_count': total_count, 'msg': '删除成功'})

dailyfresh/templates/base_detail_list.html
{# 详情页 列表页 #}
{% extends base_template %}
{% block body %}
	<div class="navbar_con">
		<div class="navbar clearfix">
			<div class="subnav_con fl">
				<h1>全部商品分类</h1>
				<span></span>
				<ul class="subnav">
					{% for type in types %}
						<li><a href="{% url 'goods:list' type.id 1 %}" class="{{type.logo}}">{{type.title}}</a></li>
					{% endfor %}
				</ul>
			</div>
			<ul class="navlist fl">
				<li><a href="">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>
    {% block main_body %}{% endblock main_body %}

{% endblock body %}

dailyfresh/templates/base_template.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
{% load static %}
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>{% block title %}{% endblock title %}</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    {# 网页顶部引入文件块 #}
    {% block top %}{% endblock top %}
</head>
<body>
{% block header %}
	<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">
				{% if user.is_authenticated %}
				<div class="login_btn fl">
					欢迎您：<em>{{user.username}}</em>
				</div>
				<span>|</span>
				<a href="{% url 'user:logout' %}">退出</a>
				{% else %}
				<div class="login_btn fl">
					<a href="{% url 'user:login' %}">登录</a>
					<span>|</span>
					<a href="{% url 'user:register' %}">注册</a>
				</div>
				{% endif %}
				<div class="user_link fl">
					<span>|</span>
					<a href="{% url 'user:user' %}">用户中心</a>
					<span>|</span>
					<a href="{% url 'user:user' %}">我的购物车</a>
					<span>|</span>
					<a href="{% url 'user:order' 1 %}">我的订单</a>
				</div>
			</div>
		</div>
	</div>
{% endblock header %}
{% block search %}
	<div class="search_bar clearfix">
		<a href="index.html" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
		<div class="search_con fl">
			<form method="get" action="/search">
				<input type="text" class="input_text fl" name="q" placeholder="搜索商品">
				<input type="submit" class="input_btn fr" name="" value="搜索">
			</form>
		</div>
		<div class="guest_cart fr">
			<a href="cart.html" class="cart_name fl">我的购物车</a>
			<div class="goods_count fl" id="show_count">{{cart_count}}</div>
		</div>
	</div>
{% endblock search %}

{% block body %}
{% endblock body %}
    <div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
    {# 网络底部html元素块 #}
    {% block html %}{% endblock html %}
    {# 网页底部引入文件块 #}
    {% block bottom %}{% endblock bottom %}
</body>
</html>

dailyfresh/templates/base_user_center.html
{# 用户中心3 #}
{% extends 'base_no_car.html' %}
{% block title %}天天生鲜用户中心{% endblock title %}
{% block midd %}用户中心{% endblock midd %}
{% block body %}
    <div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="{% url 'user:user' %}" {% if page == 'user' %}class="active"{% endif %}>· 个人信息</a></li>
				<li><a href="{% url 'user:order' 1 %}" {% if page == 'order' %}class="active"{% endif %}>· 全部订单</a></li>
				<li><a href="{% url 'user:address' %}" {% if page == 'address' %}class="active"{% endif %}>· 收货地址</a></li>
			</ul>
		</div>
        {% block right_center %}{% endblock right_center %}
    </div>
{% endblock body %}

dailyfresh/templates/detail.html
{% extends 'base_detail_list.html' %}
{% load static %}
{% block title %}天天生鲜-商品详情{% endblock title %}
{% block main_body %}
	<div class="breadcrumb">
		<a href="#">全部分类</a>
		<span>></span>
		<a href="#">{{sku.type.title}}</a>
		<span>></span>
		<a href="#">商品详情</a>
	</div>
	<div class="goods_detail_con clearfix">
		<div class="goods_detail_pic fl"><img src="{{sku.image}}"></div>

		<div class="goods_detail_list fr">
			<h3>{{sku.title}}</h3>
			<p>{{spu.detail}}</p>
			<div class="prize_bar">

				<span class="show_pirze">¥<em>{{sku.price}}</em></span>
				<span class="show_unit">单  位：{{sku.unite}}</span>
			</div>
			<div class="goods_num clearfix">
				<div class="num_name fl">数 量：</div>
				<div class="num_add fl">
					<input type="text" class="num_show fl" value="1">
					<a href="javascript:;" class="add fr">+</a>
					<a href="javascript:;" class="minus fr">-</a>	
				</div>
				<div>
					<p>其他规格：</p>
					<ul>
						{% for same_sku in same_spu %}
						<li><a href="{% url 'goods:detail' same_sku.id %}"> 其他规格：{{same_sku.title}}</a></li>
						{% endfor %}
					</ul>

				</div>
			</div>
			<div class="total">总价：<em></em></div>
			<div class="operate_btn">
				{% csrf_token %}
				<a href="javascript:;" class="buy_btn">立即购买</a>
				<a href="javascript:;" sku_id="{{sku.id}}" class="add_cart" id="add_cart">加入购物车</a>
			</div>
		</div>
	</div>

	<div class="main_wrap clearfix">
		<div class="l_wrap fl clearfix">
			<div class="new_goods">
				<h3>新品推荐</h3>
				<ul>
					{% for new in new_goods %}
						<li>
						<a href="{% url 'goods:detail' new.id %}"><img src="{{new.image}}"></a>
						<h4><a href="{% url 'goods:detail' new.id %}">{{new.title}}</a></h4>
						<div class="prize">￥{{new.price}}</div>
					</li>
					{% endfor %}
				</ul>
			</div>
		</div>

		<div class="r_wrap fr clearfix">
			<ul class="detail_tab clearfix">
				<li id="tag_detail" class="active">商品介绍</li>
				<li id="tag_comment">评论</li>
			</ul>

			<div class="tab_content" id="tab_detail">
				<dl>
					<dt>商品详情：</dt>
					<dd>{{sku.spu.spu_title|safe}}</dd>
				</dl>
			</div>
			<div class="tab_content" id="tab_comment" style="diplay: None">
				<dl>
					<dt>评论时间：{{comment.update_time}}&nbsp;&nbsp;用户名：{{comment.order.user}}</dt>
					<dd>评论内容:{{comment.comment}}</dd>
				</dl>
			</div>

		</div>
	</div>
{% endblock main_body %}
{% block bottom %}
	<div class="add_jump"></div>

	<script type="text/javascript" src="{% static 'js/jquery-1.12.2.js' %}"></script>
	<script type="text/javascript">
		$('#tag_detail').click(function(){
			$('#tag_comment').removeclass('active')
			$(this).addclass('active')
			$('#tab_comment).hidden()
			$('#tab_detail).show()
		})
		$('#tag_comment').click(function(){
			$('#tag_detail').removeclass('active')
			$(this).addclass('active')
			$('#tab_comment).show()
			$('#tab_detail).hidden()
		})
		updata_amount()
		//计算商品的总价
		function update_amount(){
				price = $('.show_pirze').children('em').text()
				count = $('.num_show').val()
				price = parseFloat(price)
				count = parseInt(count)
				amount = price*count
				$('.total').children('em').text(amount.toFixed(2)+'元')
		}
		//增加数量
		$('.add').click(function(){
				//获取原有数目
				count = $('.num_show).val()
				//加1
				count = parseInt(count)+1
				//重新设置数目
				$('.num_show).val(count)
				//重新设置商品总价
				update_amount()
		})
		//减少数量
		$('.minus').click(function{
				//获取原有数目
				count = $('.num_show).val()
				//减1
				count = parseInt(count)-1
				//重新设置数目
				$('.num_show).val(count)
				//重新设置商品总价
				update_amount()
		})
		//手动输入商品数量
		$('num_show').blur(function(){
				//获取商品数量
				count = $(this).val()
				//校验数量是否合法（输入的不是数字，是空格，数字小于0,不是整数）
				if (isNaN(count) || count.trim().length==0 || parseInt(count) <=0){
						count = 1
				}
				//重新设置商品数量
				$(this).val(parseInt(count))
				//更新总价
				update_amount()
		})

		var $add_x = $('#add_cart').offset().top;
		var $add_y = $('#add_cart').offset().left;

		var $to_x = $('#show_count').offset().top;
		var $to_y = $('#show_count').offset().left;


		$('#add_cart').click(function(){
			//获取商品的id和商品数量(获取自定义属性用attr,获取原有属性用prop)
			good_id = $(this).attr('sku_id')
			count = $('.num_show').val()
			//根据一个名字找一个input元素的值，找csrf
			csrf = $('input[name="csrfmiddlewaretoken"].val()
			//组织参数
			params = {'good_id': good_id, 'count': count, 'csrfmiddlewaretoken': csrf}
			//发起ajax post请求
			$.post('/cart/add', params, function(data){
				if(data.ret == 5){
					$(".add_jump").css({'left':$add_y+80,'top':$add_x+10,'display':'block'})
					$(".add_jump").stop().animate({
						'left': $to_y+7,
						'top': $to_x+7},
						"fast", function() {
							$(".add_jump").fadeOut('fast',function(){
								//重新设置购物车商品条目数
								$('#show_count').html(data.total_count);
							});

					});
				}
				else{
					alert(data.errmsg)
				}
			})

		})
	</script>
{% endblock bottom %}

dailyfresh/templates/index.html
{% extends 'base_template.html' %}
{% load static %}
{% block title %}天天生鲜—首页{% endblock title %}
{% block top %}
	<script type="text/javascript" src="js/jquery-1.12.4.min.js"></script>
	<script type="text/javascript" src="js/jquery-ui.min.js"></script>
	<script type="text/javascript" src="js/slide.js"></script>
{% endblock top %}
{% block body %}
	<div class="navbar_con">
		<div class="navbar">
			<h1 class="fl">全部商品分类</h1>
			<ul class="navlist fl">
				<li><a href="">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>

	<div class="center_con clearfix">
		<ul class="subnav fl">
			{% for type in types %}
				<li><a href="#model0{{forloop.counter}}" class="{{types.logo}}"></a>{{type.title}}</li>
			{% endfor %}
		</ul>
		<div class="slide fl">
			<ul class="slide_pics">
				{% for turn in turns %}
					<li><a href="{% url 'goods:detail' turn.turn_sku.id %}"></a><img src="{{turn.turns_image.url}}" alt="幻灯片"></li></li>
				{% endfor %}
			</ul>
			<div class="prev"></div>
			<div class="next"></div>
			<ul class="points"></ul>
		</div>
		<div class="adv fl">
			{% for sale in sales %}
			<a href="{{sale.good_url}}"><img src="{{sale.sales_image.url}}"></a>
			{% endfor %}
		</div>
	</div>
	{% for type in types %}
		<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model0{{forloop.counter}}">{{type.title}}</h3>
			<div class="subtitle fl">
				<span>|</span>
				{% for words in type.words %}
				<a href="{% url 'goods:detail' words.index_sku.id %}">{{words.index_sku.title}}</a>
				{% endfor %}

			</div>
			<a href="#" class="goods_more fr" id="fruit_more">查看更多 ></a>
		</div>

		<div class="goods_con clearfix">
			<div class="goods_banner fl"><img src="{{type.image.url}}"></div>
			<ul class="goods_list fl">
				{% for pics in type.pics %}
					<li>
					<h4><a href="{% url 'goods:detail' pics.index_sku.id %}">{{pics.index_sku.title}}</a></h4>
					<a href="{% url 'goods:detail' pics.index_sku.id %}"><img src="{{pics.index_sku.image.url}}"></a>
					<div class="prize">¥ {{pics.index_sku.price}}</div>
				</li>
				{% endfor %}
			</ul>
		</div>
	</div>
	{% endfor %}
{% endblock body %}


	</div>
	<script type="text/javascript" src="js/slideshow.js"></script>
	<script type="text/javascript">
		BCSlideshow('focuspic');
		var oFruit = document.getElementById('fruit_more');
		var oShownum = document.getElementById('show_count');

		var hasorder = localStorage.getItem('order_finish');

		if(hasorder)
		{
			oShownum.innerHTML = '2';
		}

		oFruit.onclick = function(){
			window.location.href = 'list.html';
		}
	</script>
</body>
</html>

dailyfresh/templates/list.html
{% extends 'base_detail_list.html' %}
{% block title %} 天天生鲜——列表页{% endblock title %}
{% block main_body %}
	<div class="breadcrumb">
		<a href="#">全部分类</a>
		<span>></span>
		<a href="#">{{type.title}}</a>
	</div>

	<div class="main_wrap clearfix">
		<div class="l_wrap fl clearfix">
			<div class="new_goods">
				<h3>新品推荐</h3>
				<ul>
					{% for new in new_goods %}
					<li>
						<a href="{% url 'goods:detail' sku.id %}"><img src="{% new.image.url} %}"></a>
						<h4><a href="{% url 'goods:detail' sku.id %}">{{new.title}}</a></h4>
						<div class="prize">￥{{new.price}}</div>
					</li>
					{% endfor %}
				</ul>
			</div>
		</div>

		<div class="r_wrap fr clearfix">
			<div class="sort_bar">

				<a href="{% url 'goods:list' type.id 1 %}" {% if sort=='default' %}class="active"{% endif %}>默认</a>
				<a href="{% url 'goods:list' type.id 1 %}?sort='price'" {% if sort=='price' %}class="active"{% endif %}>价格</a>
				<a href="{% url 'goods:list' type.id 1 %}?sort='sales'" {% if sort=='sales' %}class="active"{% endif %}>人气</a>
			</div>

			<ul class="goods_type_list clearfix">
				{% for sku in page_to.object_list %}
					<li>
					<a href="{% url 'goods:detail' sku.id %}"><img src="{% sku.image.url %}"></a>
					<h4><a href="{% url 'goods:detail' sku.id %}">{{sku.title}}</a></h4>
					<div class="operate">
						<span class="prize">￥{{sku.price}}</span>
						<span class="unit">{{sku.price}}/{{sku.count}}</span>
						<a href="#" class="add_goods" title="加入购物车"></a>
					</div>
					</li>
				{% endfor %}
			</ul>

			<div class="pagenation">
				{% if page_to.has_previous() %}
				<a href="{% url 'goods:list' type.id page_to.previous_page_number %}?sort={{sort}}"><上一页</a>
				{% endif %}
				{% for pindex in ranges %}
					{% if pindex == page_to.number %}
						<a href="{% url 'goods:list' type.id pindex %}?sort={{sort}}">{{pindex}}</a>
					{% else %}
						<a href="{% url 'goods:list' type.id pindex %}sort={{sort}}">{{pindex}}</a>
					{% endif %}
				{% endfor %}
				{% if page_to.has_next %}
					<a href="{% url 'goods:list' type.id page_to.next_page_number %}?sort={{sort}}">下一页></a>
				{% endif %}
			</div>
		</div>
	</div>
{% endblock main_body %}

dailyfresh/templates/login.html
{% extends 'base_template.html' %}
{% load staticfiles %}
{% block title %}天天生鲜-登录{% endblock title %}
{% block header %}{% endblock header %}
{% block search %}{% endblock search %}
{% block body %}
	<div class="login_top clearfix">
		<a href="index.html" class="login_logo"><img src="{% static 'images/logo02.png' %}"></a>
	</div>

	<div class="login_form_bg">
		<div class="login_form_wrap clearfix">
			<div class="login_banner fl"></div>
			<div class="slogan fl">日夜兼程 · 急速送达</div>
			<div class="login_form fr">
				<div class="login_title clearfix">
					<h1>用户登录</h1>
					<a href="{% url 'user:register' %}">立即注册</a>
				</div>
				<div class="form_input">
					{# 表单如果没写action，则默认提交到当前地址栏的url处理，在此处就是提交给/user/login/ #}

					<form method="post">
                        {% csrf_token %}
						<input type="text" name="username" class="name_input" placeholder="请输入用户名">{{username}}
						<div class="user_error">输入错误</div>
						<input type="password" name="pwd" class="pass_input" placeholder="请输入密码">
						<div class="pwd_error">输入错误</div>
						<div class="more_input clearfix">
							<input type="checkbox" name="remember" {{checked}}>
							<label>记住用户名</label>
							<a href="#">忘记密码</a>
						</div>
						<input type="submit" name="" value="登录" class="input_submit">
					</form>
				</div>
			</div>
		</div>
	</div>
	{{ errmsg }}
{% endblock body %}

dailyfresh/templates/register.html
{% extends 'base_template.html' %}
{% load staticfiles %}
{% block title %}天天生鲜-注册{% endblock title %}
{% block top %}
	<script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/register.js' %}"></script>
{% endblock top %}
{% block header %}{% endblock header %}
{% block search %}{% endblock search %}
{% block body %}
	<div class="register_con">
		<div class="l_con fl">
			<a class="reg_logo"><img src="{% static 'images/logo02.png' %}"></a>
			<div class="reg_slogan">足不出户  ·  新鲜每一天</div>
			<div class="reg_banner"></div>
		</div>

		<div class="r_con fr">
			<div class="reg_title clearfix">
				<h1>用户注册</h1>
				<a href="{% url 'user:login' %}">登录</a>
			</div>
			<div class="reg_form clearfix">
				<form method="post" action="/user/register/">
					{% csrf_token %}
				<ul>
					<li>
						<label>用户名:</label>
						<input type="text" name="user_name" id="user_name">
						<span class="error_tip">提示信息</span>
					</li>					
					<li>
						<label>密码:</label>
						<input type="password" name="pwd" id="pwd">
						<span class="error_tip">提示信息</span>
					</li>
					<li>
						<label>确认密码:</label>
						<input type="password" name="cpwd" id="cpwd">
						<span class="error_tip">提示信息</span>
					</li>
					<li>
						<label>邮箱:</label>
						<input type="text" name="email" id="email">
						<span class="error_tip">提示信息</span>
					</li>
					<li class="agreement">
						<input type="checkbox" name="allow" id="allow" checked="checked">
						<label>同意”天天生鲜用户使用协议“</label>
						<span class="error_tip2">提示信息</span>
					</li>
					<li class="reg_sub">
						<input type="submit" value="注 册" name="">
					</li>
				</ul>				
				</form>
			</div>

		</div>

	</div>
{% endblock body %}


dailyfresh/templates/user_center_info.html
{% extends 'base_user_center.html' %}
{% load staticfiles %}
{% block right_center %}
		<div class="right_content clearfix">
				<div class="info_con clearfix">
				<h3 class="common_title2">基本信息</h3>
						<ul class="user_info_list">
							<li><span>用户名：</span>{{address.user.username}}</li>
							<li><span>联系方式：</span>{{address.phone}}</li>
							<li><span>联系地址：</span>{{address.addr}}</li>
						</ul>
				</div>
				
				<h3 class="common_title2">最近浏览</h3>
				<div class="has_view_list">
				{% for sku in skus %}
				<ul class="goods_type_list clearfix">
				<li>
					{# 如果只有sku.image则只会返回nginx给的那个图片的id而不会有nginx的地址和端口号等 #}
					<a href="{% url 'goods:detail' sku.id %}"><img src="{{sku.image.url}}"></a>
					<h4><a href="{% url 'goods:detail' sku.id %}">{{sku.title}}</a></h4>
					<div class="operate">
						<span class="prize">￥{{sku.price}}</span>
						<span class="unit">{{sku.price}}/{{sku.unite}}g</span>
						<a href="#" class="add_goods" title="加入购物车"></a>
					</div>
				</li>


				</ul>
				{% endfor %}
				</div>
		</div>
{% endblock right_center %}

